egils_groups:
    resource: "@EgilsGroupsBundle/Controller/GroupController.php"
    type:     rest

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
